### ISSUE TITLE
What is the principle of the algorithm?

### ISSUE THREAD

**Issue by YuanxianH** [aj161198/Camera-Calibarator#1]
Thanks to your work. Recently I did a project about traffic monitoring. During this project, we found camera calibaration is the most critical part. I read your source code for a long time, but it a little complicated.  Would you mind talk briefly about the pipeline of your algorithm or list some your reference?

**Comment by aj161198** [comment]
Please refer to this paper - https://arxiv.org/abs/2001.07243

**Comment by YuanxianH** [comment]
> Please refer to this paper - https://arxiv.org/abs/2001.07243

Thanks! It help me a lot
